### PR TITLE
Feature/add transpile step

### PR DESCRIPTION
**Pull request by MyNameIsTakenOMG**
Originally, I do have a `CleanUp` step to remove the `tmp` folder as well as any transpiled file within in the `tryBundle` method like this 
```javascript
fs.rmSync(tmpPath, { force: true, recursive: true });
```
, but the thing is  it just did not work, so I made a compromise by adding this folder to the `.gitignore`

### CODE REVIEW

**Comment by naedx** [comment]
Hi @MyNameIsTakenOMG ! Thanks for the contribution. I have a suggestion to add to your PR. 

In my use case, I have a build runner that transpiles and bundles all lambda `.ts` files with their dependencies using esbuild. So what I pass in to the helper is already a module in `.cjs` format. How about we add an optional argument to configure the transpilation step?

```ts

fromAssetHelper(targetModule: string, config: AssetHelperConfig)

interface AssetHelperConfig {
    transpiler: TranspilerOptions
}

enum TranspilerOptions {
  Off
  Typescript,
  Esbuild
}

```

**Comment by MyNameIsTakenOMG** [comment]
> Hi @MyNameIsTakenOMG ! Thanks for the contribution. I have a suggestion to add to your PR.
> 
> In my use case, I have a build runner that transpiles and bundles all lambda `.ts` files with their dependencies using esbuild. So what I pass in to the helper is already a module in `.cjs` format. How about we add an optional argument to configure the transpilation step?
> 
> ```ts
> fromAssetHelper(targetModule: string, config: AssetHelperConfig)
> 
> interface AssetHelperConfig {
>     transpiler: TranspilerOptions
> }
> 
> enum TranspilerOptions {
>   Off
>   Typescript,
>   Esbuild
> }
> ```

Ah, I should have left some room for customization while focusing on adding this transpile step. Thank you for the heads-up 👍 Btw, I haven't used esbuild before, only spent some time taking a look at its doc tonight, so if I messed up with the build options, please let me know

**Comment by naedx** [comment]
This is awesome. Thank you for taking the time to incorporate the config and esbuild, @MyNameIsTakenOMG !

**Comment by naedx** [comment]
I was able to test and verify the esbuild step - it works just fine ! I use a config script for my esbuild to exclude the `aws-sdk/*` and `aws-lambda` modules which are already part of the lambda environment. Incorporating this could be a future enhancement but this is good for now.

**Pull request merged**
